### PR TITLE
Directly store replicate weights

### PR DESCRIPTION
**Pull request by ayushpatnaikgit**
1. Replicate weights are directly stored instead of storing the scaling factor and asking functions to do the multiplication later. 

Tests and doctests are failing. Need to be changed.

### CODE REVIEW

**Comment by smishr** [comment]
you want to fix before merging?

**Review by smishr — APPROVED** [review]
looks good. the small mistake in the `total.jl` also resolved.

**Review by smishr — COMMENTED** [review]
adding some missing checks? with `disallowmissing`

**Comment by iuliadmtru** [comment]
I am working on fixing the tests and adding more tests for this functionality. I will convert this to a draft PR until that is done.

**Comment by iuliadmtru** [comment]
Also, regarding testing, so far we've been using absolute tolerance to check correctness as compared to the equivalent R results. However, we should consider using relative tolerance instead.

For estimated standard errors we should use `rtol` and for estimated statistics, we should use `atol` (in theory) since we expect the results to be exactly the same as those in R. Hence, say,  `atol = 1e-3` should be a good tolerance for testing. However, in some cases R and Julia don't agree on rounding methods and the results end up within an absolute tolerance of 1. An example is:
Julia:
```julia
julia> apisrs = load_data("apisrs");

julia> srs = SurveyDesign(apisrs; weights = :pw) |> bootweights

julia> tot = total(:api00, srs)
1×2 DataFrame
 Row │ total      SE
     │ Float64    Float64
─────┼────────────────────
   1 │ 4.06689e6  57644.8
```

R:
```R
> srs <- svydesign(data=apisrs, weights=~pw)
> svytotal(~api00, srs)
        total    SE
api00 4066888 58241
```

An absolute tolerance of 1 is too large. Hence, I suggest we use relative tolerance for estimated statistics, as well as for estimated standard errors. This has the advantage of consistency.

There is also the case when the result is close to 0. We might get this especially for standard errors. In this case, the relative tolerance would be too high and we should use `atol`.

**Comment by iuliadmtru** [comment]
`ReplicateDesign` should be supported by `ratio` and `quantile` as well. @ayushpatnaikgit should we do this in a separate PR after this? And add tests for `ratio` and `quantile` in that PR.

**Comment by ayushpatnaikgit** [comment]
> Does bootstrapping take into account fpc? In the code fpc is not used, but I understand that bootstrapping might account for fpc implicitly. Is that true?
> 
> This is relevant for testing. I am comparing our results to the ones in R. What is the correct way to compare?
> 
> Let's take `total` and `mean` for a simple random sample using the `apisrs` dataset for example. The Julia code for generating the design and the estimates is:
> 
> ```julia
> julia> apisrs = load_data("apisrs");
> 
> julia> srs = SurveyDesign(apisrs; weights = :pw) |> bootweights;
> 
> julia> tot = total(:api00, srs)
> 1×2 DataFrame
>  Row │ total      SE
>      │ Float64    Float64
> ─────┼────────────────────
>    1 │ 4.06689e6  57644.8
> 
> julia> mn = mean(:api00, srs)
> 1×2 DataFrame
>  Row │ mean     SE
>      │ Float64  Float64
> ─────┼──────────────────
>    1 │ 656.585  9.30656
> ```
> 
> For R, I believe the corresponding code is:
> 
> ```r
> > srs <- svydesign(data=apisrs, id=~1, weights=~pw)
> > srsrep <- as.svrepdesign(srs, type="bootstrap", replicates=4000)
> > svytotal(~api00, srsrep)
>         total    SE
> api00 4066888 56295
> > svymean(~api00, srsrep)
>         mean     SE
> api00 656.58 9.0886
> ```
> 
> However, specifying fpc gives results closer to ours:
> 
> ```r
> > srs <- svydesign(data=apisrs, id=~1, weights=~pw, fpc=~fpc)
> > srsrep <- as.svrepdesign(srs, type="bootstrap", replicates=4000)
> > svytotal(~api00, srsrep)
>         total    SE
> api00 4066888 57549
> > svymean(~api00, srsrep)
>         mean     SE
> api00 656.58 9.2912
> ```
> 
> While this is not an indication that the latter is the actual corresponding code, it does make me wonder. Which one is the correct approach that I should use for testing?



> ```r
> svymean(~api00, srsrep)
> ```

I tried it with 100,000 replicates. The answers are very close to the analytical solutions of with and without fpc. So fpc matters.

**Comment by ayushpatnaikgit** [comment]
We can merge the PR once the tests and doctests are complete.

**Comment by smishr** [comment]
> We should also add back the `CategoricalArray` support.

In separate PR, not this one

**Comment by smishr** [comment]
> `ReplicateDesign` should be supported by `ratio` and `quantile` as well. @ayushpatnaikgit should we do this in a separate PR after this? And add tests for `ratio` and `quantile` in that PR.

Yes this is higher priority than `CategoricalArray`.

**Comment by iuliadmtru** [comment]
Tests now pass. I will soon get into documentation and doctests.

We should consider designing more R-independent tests.

**Comment by smishr** [comment]
documentation still failing, as not all references to analytical solutions removed in this branch. that and better docs with current branch

**Comment by ayushpatnaikgit** [comment]
@iuliadmtru can you update README.md?

**Comment by iuliadmtru** [comment]
All tests and doctests should pass now. I made some modifications:

- All text from api.md is gone. I believe that text is better fit for index.md in the tutorial/demo section. We should also have more complete docstrings where we write all the relevant information. Right now our dosctrings are lacking substance.
- There are no more references to the old designs (`SimpleRandomSample`, `StratifiedSample`) in the documentation.
- The `sturges` and `freedman_diaconis` functions are exported again. They are necessary for `hist`. However, I don't think they are relevant enough to our package to include them in the API reference. Therefore I didn't include them. `Documenter` now gives a warning because of this and I don't think we can avoid it.
- The files that I changed now have a coherent style.

There are still a few problems left:
- [] Precompiling the package gives a warning because `quantile` is defined twice. That is mentioned in issue #171 and will be fixed by PR #172.
- [] The documentation is far from complete, both the docstrings and the files inside `docs/src`. We should do a separate PR on documentation.
- [] The README is outdated. @ayushpatnaikgit I can do it, but I suggest doing it in a separate PR.

I think we can now close this PR and have a clean source code once again so that the tests for our following PRs don't fail because of this one.

**Review by smishr — APPROVED** [review]
looks good to merge

**Pull request merged**
