### PR TITLE
Add more survey datasets

### PR DESCRIPTION
**Pull request by iuliadmtru**
I added a new dataset, the Scottish Household Survey found on [this ReStore exemplar](https://www.restore.ac.uk/PEAS/exemplar2.php#started). The dataset is referenced and used in [Thomas Lumley's book](https://r-survey.r-forge.r-project.org/svybook/).

This approaches issue #72.

### CODE REVIEW

**Comment by iuliadmtru** [comment]
The doctests are failing because of PR #161. The documentation is being fixed.

**Comment by iuliadmtru** [comment]
Now the datasets from the [first 4 exemplars](https://www.restore.ac.uk/PEAS/aboutex2.php) are added. We can use them for testing.

**Comment by ayushpatnaikgit** [comment]
We need to be sure that we can publicly distribute these.

**Comment by ayushpatnaikgit** [comment]
In case you aren't confident that we can distribute these, you should have a `wget` inside your `load_data` function to download these on the fly.

**Comment by iuliadmtru** [comment]
As discussed, we should stick to the datasets that we know have a GPL license (that is, the ones in R that we first added). I believe they are enough for testing purposes, at least for now. Later, when we focus more on efficiency, we should test and benchmark using large surveys.

I am closing this PR.

**Pull request closed without merging**
